export const GRUPOS_MUSCULARES = [
	"ABDOME",
	"BICEPS",
	"COSTAS",
	"GLUTEOS",
	"MEMBROS INFERIORES GERAL",
	"MEMBROS SUPERIORES 1",
	"MEMBROS SUPERIORES 2",
	"MEMBROS SUPERIORES GERAL",
	"OMBROS",
	"PANTURRILHA",
	"PEITORAL",
	"POSTERIORES DE COXAS",
	"QUADS",
	"TRICEPS",
] as const;

export type GrupoMuscular = (typeof GRUPOS_MUSCULARES)[number];
